module.exports = {
  CURRENT_USER: {
    FETCH_CURRENT_USER: 'FETCH_CURRENT_USER',
    REMOVE_CURRENT_USER: 'REMOVE_CURRENT_USER',
  },
  POPUP: {
    CHANGE_TO_LOGIN: 'CHANGE_TO_LOGIN',
    CHANGE_TO_REGISTER: 'CHANGE_TO_REGISTER',
    EXIT_POPUP: 'EXIT_POPUP',
  },
};
